### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by Sidd1609** [Bontempogianpaolo1/continualExplain#3]
Hi, I am trying to setup your model and found that there are some missing functions, I have noted them down below: 

-> from explainers.Explainer import Label_Explainer
-> from nets.model import YandAttributes, YandConcepts
-> from mammoth.utils.tb_logger import * (no module tb_logger in mammoth.utils)
-> data loaders (I am working on this myself) 

Are the remaining modules part of some other repos or is it part of your code?
Please would you share the updated codebase?

**Comment by Bontempogianpaolo1** [comment]
Hi @Sidd1609 ,

I think it is an artifact of an older version. Try to comment the import line in YandConcept. Does the code work in that case?

**Comment by Sidd1609** [comment]
Hi @Bontempogianpaolo1, thanks for your quick reply, I did comment the lines and executed but still facing issues with the avalanche module. Pasting the error message below, 


File "training.py", line 8, in <module>
    from avalanche.avalanche.benchmarks.generators.scenario_generators import nc_benchmark
  File "/DATA/siddharth/anaconda3/envs/ContinualExplain/lib/python3.8/site-packages/avalanche/__init__.py", line 1, in <module>
    from avalanche import benchmarks
  File "/DATA/siddharth/anaconda3/envs/ContinualExplain/lib/python3.8/site-packages/avalanche/benchmarks/__init__.py", line 13, in <module>
    from .classic import *
  File "/DATA/siddharth/anaconda3/envs/ContinualExplain/lib/python3.8/site-packages/avalanche/benchmarks/classic/__init__.py", line 1, in <module>
    from .ccifar10 import *
  File "/DATA/siddharth/anaconda3/envs/ContinualExplain/lib/python3.8/site-packages/avalanche/benchmarks/classic/ccifar10.py", line 19, in <module>
    from avalanche.benchmarks.datasets import default_dataset_location
  File "/DATA/siddharth/anaconda3/envs/ContinualExplain/lib/python3.8/site-packages/avalanche/benchmarks/datasets/__init__.py", line 11, in <module>
    from .torchvision_wrapper import *
  File "/DATA/siddharth/anaconda3/envs/ContinualExplain/lib/python3.8/site-packages/avalanche/benchmarks/datasets/torchvision_wrapper.py", line 40, in <module>
    from torchvision.datasets import Kinetics400 as torchKinetics400
ImportError: cannot import name 'Kinetics400' from 'torchvision.datasets' (/DATA/siddharth/anaconda3/envs/ContinualExplain/lib/python3.8/site-packages/torchvision/datasets/__init__.py)

**Comment by Sidd1609** [comment]
-> from explainers.Explainer import Label_Explainer this file is also missing btw 
@Bontempogianpaolo1 


Please could you provide the exact pytorch and torchvision version used for this work.

**Comment by Bontempogianpaolo1** [comment]
Hi @Sidd1609 ,

Yes, other artifacts. Sorry for that, I ll try to fix it as soon as possible. In the last version we are not using avalanche and and that file is not strictly necessary to replicate the results

**Comment by Sidd1609** [comment]
Thanks, @Bontempogianpaolo1 
I am trying to run the repo with avalanche in the same folder but am getting a weird issue when importing avalanche.avalanche as it says cannot import avalanche.avalanche

**Comment by Bontempogianpaolo1** [comment]
Btw @Sidd1609 , this work is just a preliminary work of https://github.com/ema-marconato/NeSy-CL if you are interested in this topic...

**Comment by Sidd1609** [comment]
@Bontempogianpaolo1 Yes we did come across this work and are also looking at that one. We are hoping to study both works.

**Comment by Sidd1609** [comment]
Hello @Bontempogianpaolo1, were you able to get the missing files? it would really be helpful to get the benchmark results

**Comment by Bontempogianpaolo1** [comment]
Hi @Sidd1609, I have just uploaded a new version with much more material.. tell me if everything is ok now

**Comment by Sidd1609** [comment]
Hi @Bontempogianpaolo1, thank you so much for your quick reply, there is few more things needed I believe 

-> from settings import DATA_DIR, CHECKPOINT_PATH, ROOT_DIR (settings.py is missing, if it's just assigning the paths then I think I can add it directly to training.py right )

-> download from [Here](http://www.vision.caltech.edu/datasets/cub_200_2011/) I see this is given in the readme however the link is not accessible. Is this the link to the CUB dataset or something else that is needed?

**Comment by Sidd1609** [comment]
Please also mention the torch and torchvision versions that were used in this work. I am getting this issue for torchvision =1.13.0 as there are some functions deprecated.

**Comment by Bontempogianpaolo1** [comment]
Hi @Sidd1609, 
In order:
1. Exactly! You can modify them directly
2. We used the preprocessed data used by cbm. They have moved the data somewhere else. Follow their guide [here](https://github.com/yewsiang/ConceptBottleneck/tree/master/CUB)
3.  Onestly, we thought that the yaml was sufficient, and we did not notice that some packages were missing. Sorry. The entire repo is built over avalanche, mammoth, and PyTorch-lighting, and they already provide torchvision in their requirements. The code is updated until 05/2022. Installing manually again their environments (near that period) will fix this issue. Sorry for the inconvenience. If you are interested in contributing, we will accept any of your pull requests

**Comment by Sidd1609** [comment]
Hello, @Bontempogianpaolo1 thank you for the update. I am glad to inform you that I have been able to train the model on CUB. Do you support training on other datasets?

**Comment by Bontempogianpaolo1** [comment]
Excellent! While this work specifically targets CUB, I find no compelling reason why it wouldn't be applicable to other datasets as well.

**Comment by Sidd1609** [comment]
@Bontempogianpaolo1 just a follow up if one were to extend the work to other datasets what are the changes that need to made, apart from the dataloaders?

**Comment by Bontempogianpaolo1** [comment]
@Sidd1609 The significant contribution would be about dataloaders... Maybe, depending on the dataset further modification are required. What kind of data do you want to integrate?

**Comment by Sidd1609** [comment]
@Bontempogianpaolo1 we are looking at datasets such as Cifar-10 and 100 and also other similar datasets.

**Comment by Bontempogianpaolo1** [comment]
Interesting! But where do you take concept information? If you contact me by email we could talk about it

**Comment by Sidd1609** [comment]
sure!
